### ISSUE TITLE
Clients

### ISSUE THREAD

**Issue by smfuller1** [agricure/orderbook#1]
Client details that are needed in the client maintenance screen are:
Trading Title.
Invoice address.
Multiple delivery addresses, we also need to be able to add notes to each delivery address, with client contact number and details of how to obtain access to each address.
Client Code - would this be generated by us or system?
Agronomist
Need to be able to add multiple e mail addresses for each client - with ability to send them order confirmations and/or statements.
Need to be able to add account number for each supplier to the client.
Only the office to be able to add new clients.
Need to be able to delete old clients.
have attached screenshot of current client maintenance screen
<img width="786" alt="screen shot 2018-12-03 at 13 47 40" src="https://user-images.githubusercontent.com/45420650/49377506-4128fa80-f702-11e8-9a94-760e541ebecf.png">

**Comment by szolsztor** [comment]
Closing this issue and opened smaller ones in its place
