### ISSUE TITLE
Client Screen

### ISSUE THREAD

**Issue by smfuller1** [agricure/orderbook#26]
Under Profile - we need 'Trading Title' and address, and Invoice address.

Under Address - this should read - Delivery address. We need to be able to set a default delivery address. Some farms have more than one delivery address but one that is used most often.

Contacts - We need to be able to add a tick against a contact for' Purchase Order Confirmations' and 'Statements'

Invoices - should read Orders. Delivery address needs to be shown on the order and quantity needs to be in litres not packs

**Comment by szolsztor** [comment]
tracked with #33 #32 #31 #30
