### ISSUE TITLE
Client order screen

### ISSUE THREAD

**Issue by smfuller1** [agricure/orderbook#28]
I need a dropdown box per client that shows order history - as per attached.
<img width="749" alt="screenshot 2019-01-24 at 15 23 42" src="https://user-images.githubusercontent.com/45420650/51688325-3e54d280-1fec-11e9-96e2-5d16f422b973.png">

**Comment by szolsztor** [comment]
This will be added to the order screen

**Comment by szolsztor** [comment]
done
