### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by lizkirk** [agricure/orderbook#29]
Will we be able to view the products so all the active ingredient products are together for instance all the glyphosate products together or will it only list them in alphabetic order? Really we need both.
[Screenshot 2019-02-06 at 12.20.15.pdf](https://github.com/agricure/orderbook/files/2836286/Screenshot.20
[Screenshot 2019-02-06 at 12.20.15.pdf]

**Comment by szolsztor** [comment]
this is now done for the next deployment
