### ISSUE TITLE
Print out an order

### ISSUE THREAD

**Issue by lizkirk** [agricure/orderbook#35]
Not showing the comments in the notes section on the order when you go back into it to print out the confirmation.

**Comment by lizkirk** [comment]
Also must not show the prices on the orders when printing or sending the order to suppliers.
<img width="1222" alt="screenshot 2019-03-04 at 14 42 45" src="https://user-images.githubusercontent.com/46900291/53740368-ef704780-3e8b-11e9-825d-b810b93e746f.png">

**Comment by lizkirk** [comment]
Please can we also have contact details for the office and Agronomist on the print above.

**Comment by lizkirk** [comment]
We have just noticed there is no section for us to add agronomist details in.

**Comment by szolsztor** [comment]
all comments have now been fixed for next release
