### ISSUE TITLE
Enter Agronomist details

### ISSUE THREAD

**Issue by szolsztor** [agricure/orderbook#36]
We have just noticed there is no section for us to add agronomist details in.

_Originally posted by @lizkirk in https://github.com/agricure/orderbook/issues/35#issuecomment-469279249_

Do you mean the Agronomist who is assigned to the order? This will be there once we enabled authentication

**Comment by szolsztor** [comment]
@smfuller1 what agronomist details do I need to capture? So far I only have name and email address

**Comment by lizkirk** [comment]
Mobile number please 

Thanks 
Liz

**Comment by szolsztor** [comment]
this is done for the next release
