### ISSUE TITLE
Please can we also have contact details for the office and Agronomist on the print above.

### ISSUE THREAD

**Issue by szolsztor** [agricure/orderbook#37]
Please can we also have contact details for the office and Agronomist on the print above.

_Originally posted by @lizkirk in https://github.com/agricure/orderbook/issues/35#issuecomment-469278899_

What do you mean by the office? Agricure?

**Comment by szolsztor** [comment]
Do you have a sample order print you can upload? i will make it a copy of that then

**Comment by lizkirk** [comment]
Hi Paul,

Please find copy of Purchase Order that goes out to the supplier.
[PurchaseOrder - Agricure Ltd.pdf](https://github.com/agricure/orderbook/files/2965850/PurchaseOrder.-.Agricure.Ltd.pdf)

**Comment by szolsztor** [comment]
this is now done
