### ISSUE TITLE
help distinguish clients in order screen

### ISSUE THREAD

**Issue by szolsztor** [agricure/orderbook#42]
Orders
We have added J Beaty as a new client but we can’t then select which Beaty in the order screen - we need a dropdown box
to see all the clients with the same name.

@smfuller1 is there information i can show to help show the differences between the clients? like farm address, etc?

**Comment by smfuller1** [comment]
we just need a dropdown box which will display all the beaty’s?

**Comment by szolsztor** [comment]
i did have it as a drop down, but Rob wanted it to be a search box

do you want both? where you can search and if there is more than 1 it provides a drop down?

**Comment by smfuller1** [comment]
yes please
