### ISSUE TITLE
system generated client codes

### ISSUE THREAD

**Issue by szolsztor** [agricure/orderbook#8]
Why does the system need to generated unique client codes? What does this help with?

**Comment by smfuller1** [comment]
to differentiate between clients - when we add a client we generate a code. Its a relic from the old system. Its just an account number.

**Comment by szolsztor** [comment]
if you still need this I can have it auto-generated, would you need any of the following:

- [ ] a specific format
- [ ] to be able to edit the code so you can use existing codes from the current system

**Comment by szolsztor** [comment]
closing this in favor of #11
